package br.ol.g2d.editor;

import br.ol.g2d.G2DContext;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * MainFrame class.
 * 
 * @author Leonardo Ono (ono.leo@gmail.com)
 */
public class MainFrame extends javax.swing.JFrame {
    
    public static final String BUILD = "21022017";
    private final G2DContext context = new G2DContext();
    private final NewG2DDialog newSpriteSheetDialog;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("G2D Editor - Build #" + BUILD);
        setSize(800, 600);
        setLocationRelativeTo(null);
        newSpriteSheetDialog = new NewG2DDialog(this, true);
        setContext();
        init();
        registerMessageReceivers();
        context.update();
    }

    private void setContext() {
        newSpriteSheetDialog.setContext(context);
        spriteSheetPanel2.setContext(context);
        spritePanel1.setContext(context);
        palettePanel2.setContext(context);
        paletteColorInfoPanel1.setContext(context);
        spriteInfoPanel1.setContext(context);
        animationPreviewPanel1.setContext(context);
        animationTimeLinePanel1.setContext(context);
        animationsListPanel2.setContext(context);
        animationPropertiesEditor1.setContext(context);
        animationObjectKeyframePropertiesEditor1.setContext(context);
        animationBakingScript1.setContext(context);
        bitmapFontsListPanel1.setContext(context);
        bitmapFontPreviewPanel1.setContext(context);
        bitmapFontScreensListPanel1.setContext(context);
        bitmapTextScreenPreviewPanel1.setContext(context);
        bitmapTextScreenPropertiesEditor1.setContext(context);
    }
    
    private void init() {
        spriteSheetPanel2.init();
        spritePanel1.init();
        palettePanel2.init();
        paletteColorInfoPanel1.init();
        spriteInfoPanel1.init();
        animationPreviewPanel1.init();
        animationTimeLinePanel1.init();
        animationsListPanel2.init();
        animationPropertiesEditor1.init();
        animationObjectKeyframePropertiesEditor1.init();
        animationBakingScript1.init();
        bitmapFontsListPanel1.init();
        bitmapFontPreviewPanel1.init();
        bitmapFontScreensListPanel1.init();
        bitmapTextScreenPreviewPanel1.init();
        bitmapTextScreenPropertiesEditor1.init();
    }
    
    private void registerMessageReceivers() {
        context.registerAsMessageReceiver(this);
        context.registerAsMessageReceiver(spriteSheetPanel2);
        context.registerAsMessageReceiver(spritePanel1);
        context.registerAsMessageReceiver(palettePanel2);
        context.registerAsMessageReceiver(paletteColorInfoPanel1);
        context.registerAsMessageReceiver(spriteInfoPanel1);
        context.registerAsMessageReceiver(animationPreviewPanel1);
        context.registerAsMessageReceiver(animationTimeLinePanel1);
        context.registerAsMessageReceiver(animationsListPanel2);
        context.registerAsMessageReceiver(animationPropertiesEditor1);
        context.registerAsMessageReceiver(animationObjectKeyframePropertiesEditor1);
        context.registerAsMessageReceiver(animationBakingScript1);
        context.registerAsMessageReceiver(bitmapFontsListPanel1);
        context.registerAsMessageReceiver(bitmapFontPreviewPanel1);
        context.registerAsMessageReceiver(bitmapFontScreensListPanel1);
        context.registerAsMessageReceiver(bitmapTextScreenPreviewPanel1);
        context.registerAsMessageReceiver(bitmapTextScreenPropertiesEditor1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        scrollPane1 = new br.ol.ui.view.ScrollPane();
        spriteSheetPanel2 = new br.ol.g2d.editor.spritesheet.SpriteSheetPanel();
        spriteInfoPanel1 = new br.ol.g2d.editor.sprite.SpriteInfoPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane6 = new javax.swing.JSplitPane();
        scrollPane2 = new br.ol.ui.view.ScrollPane();
        spritePanel1 = new br.ol.g2d.editor.sprite.SpritePanel();
        jPanel2 = new javax.swing.JPanel();
        scrollPane4 = new br.ol.ui.view.ScrollPane();
        palettePanel2 = new br.ol.g2d.editor.palette.PalettePanel();
        paletteColorInfoPanel1 = new br.ol.g2d.editor.palette.PaletteColorInfoPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        scrollPane5 = new br.ol.ui.view.ScrollPane();
        animationPreviewPanel1 = new br.ol.g2d.editor.animation.preview.AnimationPreviewPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        scrollPane6 = new br.ol.ui.view.ScrollPane();
        animationTimeLinePanel1 = new br.ol.g2d.editor.animation.timeline.AnimationTimeLinePanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollPane3 = new br.ol.ui.view.ScrollPane();
        animationsListPanel2 = new br.ol.g2d.editor.animation.list.AnimationsListPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        animationPropertiesEditor1 = new br.ol.g2d.editor.animation.properties.AnimationPropertiesEditor();
        jScrollPane2 = new javax.swing.JScrollPane();
        animationObjectKeyframePropertiesEditor1 = new br.ol.g2d.editor.animation.properties.AnimationObjectKeyframePropertiesEditor();
        animationBakingScript1 = new br.ol.g2d.editor.animation.scripting.AnimationBakingScript();
        jSplitPane5 = new javax.swing.JSplitPane();
        jSplitPane7 = new javax.swing.JSplitPane();
        scrollPane8 = new br.ol.ui.view.ScrollPane();
        bitmapFontPreviewPanel1 = new br.ol.g2d.editor.text.font.preview.BitmapFontPreviewPanel();
        jPanel4 = new javax.swing.JPanel();
        scrollPane7 = new br.ol.ui.view.ScrollPane();
        bitmapFontsListPanel1 = new br.ol.g2d.editor.text.font.list.BitmapFontsListPanel();
        jLabel2 = new javax.swing.JLabel();
        jSplitPane8 = new javax.swing.JSplitPane();
        scrollPane10 = new br.ol.ui.view.ScrollPane();
        bitmapTextScreenPreviewPanel1 = new br.ol.g2d.editor.text.screen.preview.BitmapTextScreenPreviewPanel();
        jSplitPane9 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bitmapTextScreenPropertiesEditor1 = new br.ol.g2d.editor.text.screen.property.BitmapTextScreenPropertiesEditor();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        scrollPane9 = new br.ol.ui.view.ScrollPane();
        bitmapFontScreensListPanel1 = new br.ol.g2d.editor.text.screen.list.BitmapFontScreensListPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemNew = new javax.swing.JMenuItem();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemSaveAs = new javax.swing.JMenuItem();
        menuItemClose = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(450);
        jSplitPane1.setOneTouchExpandable(true);

        javax.swing.GroupLayout spriteSheetPanel2Layout = new javax.swing.GroupLayout(spriteSheetPanel2);
        spriteSheetPanel2.setLayout(spriteSheetPanel2Layout);
        spriteSheetPanel2Layout.setHorizontalGroup(
            spriteSheetPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        spriteSheetPanel2Layout.setVerticalGroup(
            spriteSheetPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        scrollPane1.setViewportView(spriteSheetPanel2);

        javax.swing.GroupLayout spriteInfoPanel1Layout = new javax.swing.GroupLayout(spriteInfoPanel1);
        spriteInfoPanel1.setLayout(spriteInfoPanel1Layout);
        spriteInfoPanel1Layout.setHorizontalGroup(
            spriteInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spriteInfoPanel1Layout.setVerticalGroup(
            spriteInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
            .addComponent(spriteInfoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spriteInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Sprite Sheet", jPanel1);

        jSplitPane1.setLeftComponent(jTabbedPane2);

        jSplitPane6.setDividerLocation(400);
        jSplitPane6.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout spritePanel1Layout = new javax.swing.GroupLayout(spritePanel1);
        spritePanel1.setLayout(spritePanel1Layout);
        spritePanel1Layout.setHorizontalGroup(
            spritePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        spritePanel1Layout.setVerticalGroup(
            spritePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        scrollPane2.setViewportView(spritePanel1);

        jSplitPane6.setTopComponent(scrollPane2);

        javax.swing.GroupLayout palettePanel2Layout = new javax.swing.GroupLayout(palettePanel2);
        palettePanel2.setLayout(palettePanel2Layout);
        palettePanel2Layout.setHorizontalGroup(
            palettePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        palettePanel2Layout.setVerticalGroup(
            palettePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        scrollPane4.setViewportView(palettePanel2);

        javax.swing.GroupLayout paletteColorInfoPanel1Layout = new javax.swing.GroupLayout(paletteColorInfoPanel1);
        paletteColorInfoPanel1.setLayout(paletteColorInfoPanel1Layout);
        paletteColorInfoPanel1Layout.setHorizontalGroup(
            paletteColorInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        paletteColorInfoPanel1Layout.setVerticalGroup(
            paletteColorInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paletteColorInfoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(paletteColorInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
        );

        jSplitPane6.setRightComponent(jPanel2);

        jTabbedPane1.addTab("Sprite Editor", jSplitPane6);

        jSplitPane2.setDividerLocation(300);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout animationPreviewPanel1Layout = new javax.swing.GroupLayout(animationPreviewPanel1);
        animationPreviewPanel1.setLayout(animationPreviewPanel1Layout);
        animationPreviewPanel1Layout.setHorizontalGroup(
            animationPreviewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        animationPreviewPanel1Layout.setVerticalGroup(
            animationPreviewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        scrollPane5.setViewportView(animationPreviewPanel1);

        jSplitPane2.setLeftComponent(scrollPane5);

        jSplitPane3.setDividerLocation(50);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout animationTimeLinePanel1Layout = new javax.swing.GroupLayout(animationTimeLinePanel1);
        animationTimeLinePanel1.setLayout(animationTimeLinePanel1Layout);
        animationTimeLinePanel1Layout.setHorizontalGroup(
            animationTimeLinePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        animationTimeLinePanel1Layout.setVerticalGroup(
            animationTimeLinePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        scrollPane6.setViewportView(animationTimeLinePanel1);

        jSplitPane3.setTopComponent(scrollPane6);

        jSplitPane4.setDividerLocation(200);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Animations:");

        javax.swing.GroupLayout animationsListPanel2Layout = new javax.swing.GroupLayout(animationsListPanel2);
        animationsListPanel2.setLayout(animationsListPanel2Layout);
        animationsListPanel2Layout.setHorizontalGroup(
            animationsListPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        animationsListPanel2Layout.setVerticalGroup(
            animationsListPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        scrollPane3.setViewportView(animationsListPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(jPanel3);

        animationPropertiesEditor1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(animationPropertiesEditor1);

        jTabbedPane3.addTab("Animation Properties", jScrollPane1);

        jScrollPane2.setViewportView(animationObjectKeyframePropertiesEditor1);

        jTabbedPane3.addTab("Keyframe Properties", jScrollPane2);
        jTabbedPane3.addTab("Animation Baking Script", animationBakingScript1);

        jSplitPane4.setRightComponent(jTabbedPane3);

        jSplitPane3.setBottomComponent(jSplitPane4);

        jSplitPane2.setRightComponent(jSplitPane3);

        jTabbedPane1.addTab("Animation Editor", jSplitPane2);

        jSplitPane5.setDividerLocation(200);
        jSplitPane5.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane7.setDividerLocation(200);

        javax.swing.GroupLayout bitmapFontPreviewPanel1Layout = new javax.swing.GroupLayout(bitmapFontPreviewPanel1);
        bitmapFontPreviewPanel1.setLayout(bitmapFontPreviewPanel1Layout);
        bitmapFontPreviewPanel1Layout.setHorizontalGroup(
            bitmapFontPreviewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        bitmapFontPreviewPanel1Layout.setVerticalGroup(
            bitmapFontPreviewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        scrollPane8.setViewportView(bitmapFontPreviewPanel1);

        jSplitPane7.setRightComponent(scrollPane8);

        javax.swing.GroupLayout bitmapFontsListPanel1Layout = new javax.swing.GroupLayout(bitmapFontsListPanel1);
        bitmapFontsListPanel1.setLayout(bitmapFontsListPanel1Layout);
        bitmapFontsListPanel1Layout.setHorizontalGroup(
            bitmapFontsListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        bitmapFontsListPanel1Layout.setVerticalGroup(
            bitmapFontsListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        scrollPane7.setViewportView(bitmapFontsListPanel1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Bitmap Text Fonts:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
        );

        jSplitPane7.setLeftComponent(jPanel4);

        jSplitPane5.setTopComponent(jSplitPane7);

        jSplitPane8.setDividerLocation(200);

        javax.swing.GroupLayout bitmapTextScreenPreviewPanel1Layout = new javax.swing.GroupLayout(bitmapTextScreenPreviewPanel1);
        bitmapTextScreenPreviewPanel1.setLayout(bitmapTextScreenPreviewPanel1Layout);
        bitmapTextScreenPreviewPanel1Layout.setHorizontalGroup(
            bitmapTextScreenPreviewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        bitmapTextScreenPreviewPanel1Layout.setVerticalGroup(
            bitmapTextScreenPreviewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        scrollPane10.setViewportView(bitmapTextScreenPreviewPanel1);

        jSplitPane8.setRightComponent(scrollPane10);

        jSplitPane9.setDividerLocation(200);
        jSplitPane9.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Screen Properties:");

        jScrollPane3.setViewportView(bitmapTextScreenPropertiesEditor1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
        );

        jSplitPane9.setBottomComponent(jPanel6);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Bitmap Text Screens:");

        javax.swing.GroupLayout bitmapFontScreensListPanel1Layout = new javax.swing.GroupLayout(bitmapFontScreensListPanel1);
        bitmapFontScreensListPanel1.setLayout(bitmapFontScreensListPanel1Layout);
        bitmapFontScreensListPanel1Layout.setHorizontalGroup(
            bitmapFontScreensListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );
        bitmapFontScreensListPanel1Layout.setVerticalGroup(
            bitmapFontScreensListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        scrollPane9.setViewportView(bitmapFontScreensListPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
            .addComponent(scrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
        );

        jSplitPane9.setLeftComponent(jPanel5);

        jSplitPane8.setLeftComponent(jSplitPane9);

        jSplitPane5.setRightComponent(jSplitPane8);

        jTabbedPane1.addTab("Bitmap Text", jSplitPane5);

        jSplitPane1.setRightComponent(jTabbedPane1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        menuFile.setText("File");

        menuItemNew.setText("New");
        menuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewActionPerformed(evt);
            }
        });
        menuFile.add(menuItemNew);

        menuItemOpen.setText("Open");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuItemOpen);

        menuItemSave.setText("Save");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSave);

        menuItemSaveAs.setText("Save As ...");
        menuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveAsActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSaveAs);

        menuItemClose.setText("Close");
        menuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCloseActionPerformed(evt);
            }
        });
        menuFile.add(menuItemClose);

        jMenuBar1.add(menuFile);

        menuHelp.setText("Help");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });

        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCloseActionPerformed
        context.close();
    }//GEN-LAST:event_menuItemCloseActionPerformed

    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        try {
            String filename = null;
            if (context.getData().getFilename() == null) {
                JFileChooser fileChooser = new JFileChooser();
                int result = fileChooser.showSaveDialog(this);
                if (result == JFileChooser.CANCEL_OPTION) {
                    return;
                }
                File file = fileChooser.getSelectedFile();
                filename = file.getPath();
            }
            else {
                filename = context.getData().getFilename();
            }
            context.save(filename);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Exception: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void menuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewActionPerformed
        newSpriteSheetDialog.setLocationRelativeTo(this);
        newSpriteSheetDialog.setVisible(true);
    }//GEN-LAST:event_menuItemNewActionPerformed

    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.CANCEL_OPTION) {
                return;
            }
            File file = fileChooser.getSelectedFile();
            context.load(file.getPath());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Exception: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemOpenActionPerformed

    private void menuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveAsActionPerformed
        try {
            String filename = null;
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showSaveDialog(this);
            if (result == JFileChooser.CANCEL_OPTION) {
                return;
            }
            File file = fileChooser.getSelectedFile();
            filename = file.getPath();
            context.save(filename);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Exception: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemSaveAsActionPerformed

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
    }//GEN-LAST:event_menuHelpActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        JOptionPane.showMessageDialog(this, "G2D Editor\n\nDeveloped by Leonardo Ono (ono.leo@gmail.com)\nBuild #" + BUILD, "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.ol.g2d.editor.animation.scripting.AnimationBakingScript animationBakingScript1;
    private br.ol.g2d.editor.animation.properties.AnimationObjectKeyframePropertiesEditor animationObjectKeyframePropertiesEditor1;
    private br.ol.g2d.editor.animation.preview.AnimationPreviewPanel animationPreviewPanel1;
    private br.ol.g2d.editor.animation.properties.AnimationPropertiesEditor animationPropertiesEditor1;
    private br.ol.g2d.editor.animation.timeline.AnimationTimeLinePanel animationTimeLinePanel1;
    private br.ol.g2d.editor.animation.list.AnimationsListPanel animationsListPanel2;
    private br.ol.g2d.editor.text.font.preview.BitmapFontPreviewPanel bitmapFontPreviewPanel1;
    private br.ol.g2d.editor.text.screen.list.BitmapFontScreensListPanel bitmapFontScreensListPanel1;
    private br.ol.g2d.editor.text.font.list.BitmapFontsListPanel bitmapFontsListPanel1;
    private br.ol.g2d.editor.text.screen.preview.BitmapTextScreenPreviewPanel bitmapTextScreenPreviewPanel1;
    private br.ol.g2d.editor.text.screen.property.BitmapTextScreenPropertiesEditor bitmapTextScreenPropertiesEditor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JSplitPane jSplitPane7;
    private javax.swing.JSplitPane jSplitPane8;
    private javax.swing.JSplitPane jSplitPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemClose;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemSaveAs;
    private br.ol.g2d.editor.palette.PaletteColorInfoPanel paletteColorInfoPanel1;
    private br.ol.g2d.editor.palette.PalettePanel palettePanel2;
    private br.ol.ui.view.ScrollPane scrollPane1;
    private br.ol.ui.view.ScrollPane scrollPane10;
    private br.ol.ui.view.ScrollPane scrollPane2;
    private br.ol.ui.view.ScrollPane scrollPane3;
    private br.ol.ui.view.ScrollPane scrollPane4;
    private br.ol.ui.view.ScrollPane scrollPane5;
    private br.ol.ui.view.ScrollPane scrollPane6;
    private br.ol.ui.view.ScrollPane scrollPane7;
    private br.ol.ui.view.ScrollPane scrollPane8;
    private br.ol.ui.view.ScrollPane scrollPane9;
    private br.ol.g2d.editor.sprite.SpriteInfoPanel spriteInfoPanel1;
    private br.ol.g2d.editor.sprite.SpritePanel spritePanel1;
    private br.ol.g2d.editor.spritesheet.SpriteSheetPanel spriteSheetPanel2;
    // End of variables declaration//GEN-END:variables
    
    public void update() {
        menuFile.setEnabled(true);
        menuItemNew.setEnabled(context.getData() == null);
        menuItemOpen.setEnabled(context.getData() == null);
        menuItemSave.setEnabled(context.getData() != null);
        menuItemSaveAs.setEnabled(context.getData() != null);
        menuItemClose.setEnabled(context.getData() != null);
        menuHelp.setEnabled(true);
        repaint();
    }
    
}
